### ISSUE TITLE
The enrolment does not seem to work anymore

### ISSUE THREAD

**Issue by just1c** [rposbo/speechrecognitionapi#1]
Hi Robin,

I tried using my API key and endpoint but the demo page does not seem to work for me? was wondering if your api keys and endpoint still work?

thanks,

Justice

**Comment by rposbo** [comment]
Hi Justice! 

I think you might have raised this issue on the wrong repo: this one is for the [speech recognition API](https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition) that's built into modern browsers, not the microsoft one. 

Just head over to https://rposbo.github.io/speechrecognitionapi/ hit the mic, be sure to "allow" mic access, and start talking; your words should appear in the banner at the top of the page.

Perhaps you meant to raise the issue against this one? https://github.com/rposbo/speaker-recognition-api ?

If so, can you please raise it there and I'll investigate? 

(If you got to this repo via an incorrect link on my blog, can you let me know too?.. thank you!)
